#  Data Engineering Project
# Student Performance Monitoring üìö

**Team Members:**  
- Eng. Rimas Alharthi - 444004103
- Eng. Ghaida Bukhari - 444002930
- Eng. Razan Aloatibi - 444004683
- Eng. Asool Rajab -  444002958

---------------------------------------------------------------------------------------------
## üóÑÔ∏è Phase 1: Relational Database ‚Äì Structured Data Storage & Queries

In [1]:
from google.colab import files
uploaded = files.upload()

Saving StudentPerformanceFactors.csv to StudentPerformanceFactors.csv

In [2]:
# Install SQLite libraries
import sqlite3
import pandas as pd
import time

#  Load dataset
df = pd.read_csv('/content/StudentPerformanceFactors.csv')
df.head()

#Create an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

In [3]:
# Create the students table
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER PRIMARY KEY,
    gender TEXT,
    distance_from_home TEXT,
    parental_education_level TEXT,
    learning_disabilities TEXT,
    parental_involvement TEXT,
    access_to_resources TEXT,
    extracurricular_activities TEXT,
    sleep_hours REAL,
    internet_access TEXT,
    family_income REAL,
    school_type TEXT,
    peer_influence TEXT,
    physical_activity REAL
)
""")
conn.commit()
print("‚úÖ Student Table created")

‚úÖ Student Table created

In [4]:
# Create AcademicPerformance table
cursor.execute("""
CREATE TABLE AcademicPerformance (
    acadamic_no INTEGER PRIMARY KEY,
    student_id INTEGER,
    hours_studied INTEGER,
    attendance INTEGER,
    previous_scores INTEGER,
    motivation_level TEXT,
    tutoring_sessions INTEGER,
    teacher_quality TEXT,
    exam_score INTEGER,
    FOREIGN KEY (student_id) REFERENCES students(student_id)
);
""")

conn.commit()
print("‚úÖ Academic Performance Table created")

‚úÖ Academic Performance Table created

In [5]:
# Extract relevant student-related columns from the original DataFrame,
# rename them to match the 'students' table schema, and insert the cleaned data into the SQLite database.

students_df = df[['Student_Id', 'Gender', 'Distance_from_Home', 'Parental_Education_Level',
                  'Learning_Disabilities', 'Parental_Involvement', 'Access_to_Resources',
                  'Extracurricular_Activities', 'Sleep_Hours', 'Internet_Access', 'Family_Income',
                  'School_Type', 'Peer_Influence', 'Physical_Activity']].drop_duplicates()

students_df.columns = ['student_id', 'gender', 'distance_from_home', 'parental_education_level',
                       'learning_disabilities', 'parental_involvement', 'access_to_resources',
                       'extracurricular_activities', 'sleep_hours', 'internet_access', 'family_income',
                       'school_type', 'peer_influence', 'physical_activity']

students_df.to_sql('students', conn, if_exists='append', index=False)

6607

In [6]:
# Extract academic performance-related columns from the original dataset,
# rename them to match the 'academic_performance' table schema, and insert the cleaned data into the SQLite database.

performance_df = df[['Acadamic_No', 'Student_Id', 'Hours_Studied', 'Attendance',
                     'Previous_Scores', 'Motivation_Level', 'Tutoring_Sessions',
                     'Teacher_Quality', 'Exam_Score']]

performance_df.columns = ['acadamic_no', 'student_id', 'hours_studied', 'attendance',
                          'previous_scores', 'motivation_level', 'tutoring_sessions',
                          'teacher_quality', 'exam_score']

performance_df.to_sql('academic_performance', conn, if_exists='append', index=False)

6607

# CRUD operations:

In [7]:
# üìã View Student table BEFORE CRUD operations
print("üéì Students Table BEFORE CRUD:")
pd.read_sql_query("SELECT * FROM students LIMIT 10", conn)

üéì Students Table BEFORE CRUD:

,student_id,gender,distance_from_home,parental_education_level,learning_disabilities,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,internet_access,family_income,school_type,peer_influence,physical_activity
0,1003,Male,Far,College,No,High,High,Yes,7.0,No,Low,Public,Neutral,2.0
1,1005,Male,Moderate,College,No,Medium,High,Yes,8.0,Yes,Low,Private,Positive,3.0
2,1006,Male,Moderate,High School,No,High,Medium,Yes,9.0,Yes,Medium,Public,Positive,3.0
3,1008,Male,Near,High School,No,Medium,High,Yes,8.0,Yes,Low,Private,Positive,4.0
4,1009,Male,Near,High School,No,Medium,Low,Yes,5.0,No,Low,Public,Neutral,3.0
5,1010,Male,Moderate,College,No,Low,Medium,No,6.0,Yes,High,Public,Neutral,3.0
6,1011,Female,Far,Postgraduate,No,High,High,Yes,9.0,Yes,Medium,Public,Neutral,2.0
7,1012,Male,Moderate,College,No,Medium,Medium,No,4.0,Yes,Low,Public,Negative,4.0
8,1013,Male,Near,High School,No,Medium,Low,Yes,6.0,Yes,Medium,Public,Positive,3.0
9,1014,Female,Far,High School,No,High,Low,No,6.0,Yes,Medium,Private,Neutral,2.0

In [8]:
# üìã View Academic Performance Table BEFORE CRUD operations
print("\nüìö Academic Performance Table BEFORE CRUD:")
pd.read_sql_query("SELECT * FROM academic_performance LIMIT 10", conn)

üìö Academic Performance Table BEFORE CRUD:

,acadamic_no,student_id,hours_studied,attendance,previous_scores,motivation_level,tutoring_sessions,teacher_quality,exam_score
0,1,4429,23,84,73,Low,0,Medium,67
1,2,1095,19,64,59,Low,2,Medium,61
2,3,4180,24,98,91,Medium,2,Medium,74
3,4,9675,29,89,98,Medium,1,Medium,71
4,5,4722,19,92,65,Medium,3,High,70
5,6,2336,19,88,89,Medium,3,Medium,71
6,7,4400,29,84,68,Low,1,Medium,67
7,8,6989,25,78,50,Medium,1,High,66
8,9,6616,17,94,80,High,0,Low,69
9,10,2612,23,98,71,Medium,0,High,72

## Create

In [9]:
#create new recored in both tables
cursor.execute("""
INSERT INTO students (
    student_id, gender, distance_from_home, parental_education_level,
    learning_disabilities, parental_involvement, access_to_resources,
    extracurricular_activities, sleep_hours, internet_access,
    family_income, school_type, peer_influence, physical_activity
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", (7034, "Male", "Far", "High School", "Yes", "Medium", "Low", "No", 6.0, "No", "Low", "Public", "Negative", 2.0))

cursor.execute("""
INSERT INTO academic_performance (
    acadamic_no, student_id, hours_studied, attendance, previous_scores,
    motivation_level, tutoring_sessions, teacher_quality, exam_score
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
""", (6608, 7034, 6, 90, 75, "High", 2, "High", 88))

pd.read_sql_query("SELECT * FROM academic_performance WHERE acadamic_no = 6608", conn)
pd.read_sql_query("SELECT * FROM students WHERE student_id = 7034", conn)

,student_id,gender,distance_from_home,parental_education_level,learning_disabilities,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,internet_access,family_income,school_type,peer_influence,physical_activity
0,7034,Male,Far,High School,Yes,Medium,Low,No,6.0,No,Low,Public,Negative,2.0

## Update

In [10]:
# Update existing record
cursor.execute("""
UPDATE academic_performance
SET exam_score = 91, tutoring_sessions = 3
WHERE acadamic_no = 6608
""")

conn.commit()
print("\n ‚úÖ Academic performance updated.")
pd.read_sql_query("SELECT * FROM academic_performance WHERE acadamic_no = 6608", conn)

 ‚úÖ Academic performance updated.

,acadamic_no,student_id,hours_studied,attendance,previous_scores,motivation_level,tutoring_sessions,teacher_quality,exam_score
0,6608,7034,6,90,75,High,3,High,91

## Delete:

In [11]:
# Delete existing record
cursor.execute("DELETE FROM academic_performance WHERE acadamic_no = 3")
cursor.execute("DELETE FROM students WHERE student_id = 4180")
conn.commit()
print("‚úÖ Academic performance deleted.")

‚úÖ Academic performance deleted.

## Read

In [12]:
# üìã View tables After CRUD operations
print("üéì Students Table After CRUD:")
pd.read_sql_query("SELECT * FROM students LIMIT 10", conn)

üéì Students Table After CRUD:

,student_id,gender,distance_from_home,parental_education_level,learning_disabilities,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,internet_access,family_income,school_type,peer_influence,physical_activity
0,1003,Male,Far,College,No,High,High,Yes,7.0,No,Low,Public,Neutral,2.0
1,1005,Male,Moderate,College,No,Medium,High,Yes,8.0,Yes,Low,Private,Positive,3.0
2,1006,Male,Moderate,High School,No,High,Medium,Yes,9.0,Yes,Medium,Public,Positive,3.0
3,1008,Male,Near,High School,No,Medium,High,Yes,8.0,Yes,Low,Private,Positive,4.0
4,1009,Male,Near,High School,No,Medium,Low,Yes,5.0,No,Low,Public,Neutral,3.0
5,1010,Male,Moderate,College,No,Low,Medium,No,6.0,Yes,High,Public,Neutral,3.0
6,1011,Female,Far,Postgraduate,No,High,High,Yes,9.0,Yes,Medium,Public,Neutral,2.0
7,1012,Male,Moderate,College,No,Medium,Medium,No,4.0,Yes,Low,Public,Negative,4.0
8,1013,Male,Near,High School,No,Medium,Low,Yes,6.0,Yes,Medium,Public,Positive,3.0
9,1014,Female,Far,High School,No,High,Low,No,6.0,Yes,Medium,Private,Neutral,2.0

In [13]:
# üìã View tables After CRUD operations
print("\nüìö Academic Performance Table After CRUD:")
pd.read_sql_query("SELECT * FROM academic_performance LIMIT 10", conn)

üìö Academic Performance Table After CRUD:

,acadamic_no,student_id,hours_studied,attendance,previous_scores,motivation_level,tutoring_sessions,teacher_quality,exam_score
0,1,4429,23,84,73,Low,0,Medium,67
1,2,1095,19,64,59,Low,2,Medium,61
2,4,9675,29,89,98,Medium,1,Medium,71
3,5,4722,19,92,65,Medium,3,High,70
4,6,2336,19,88,89,Medium,3,Medium,71
5,7,4400,29,84,68,Low,1,Medium,67
6,8,6989,25,78,50,Medium,1,High,66
7,9,6616,17,94,80,High,0,Low,69
8,10,2612,23,98,71,Medium,0,High,72
9,11,7184,17,80,88,Medium,4,High,68

## SQLite Queries

In [14]:
# Top 5 students with best exam scores
print("üèÜ Top 5 students by exam score:")
query = """SELECT s.*, ap.exam_score
FROM students s
JOIN academic_performance ap
ON s.student_id = ap.student_id
ORDER BY ap.exam_score DESC
LIMIT 5;"""
pd.read_sql_query(query, conn)

üèÜ Top 5 students by exam score:

,student_id,gender,distance_from_home,parental_education_level,learning_disabilities,parental_involvement,access_to_resources,extracurricular_activities,sleep_hours,internet_access,family_income,school_type,peer_influence,physical_activity,exam_score
0,8230,Female,Moderate,High School,No,Low,Medium,Yes,6.0,No,High,Public,Positive,3.0,101
1,9182,Female,Near,College,No,High,Medium,Yes,4.0,Yes,High,Private,Positive,2.0,100
2,5220,Male,Far,High School,No,High,High,Yes,4.0,Yes,Medium,Public,Negative,3.0,99
3,3439,Female,Near,High School,No,High,High,Yes,8.0,Yes,Medium,Private,Negative,2.0,99
4,4265,Female,Moderate,College,No,Low,Medium,Yes,9.0,Yes,Medium,Public,Positive,2.0,98

In [15]:
# Average exam score by gender
print("\nüìä Average exam score by gender:")
query = """
SELECT s.gender, AVG(ap.exam_score) AS avg_score
FROM students s
JOIN academic_performance ap
ON s.student_id = ap.student_id
GROUP BY s.gender;
"""
pd.read_sql_query(query, conn)

üìä Average exam score by gender:

   gender  avg_score
0  Female  67.244898
1    Male  67.233351

## Performance Optimization with Index

In [16]:
# Query before index (from academic_performance)
start = time.time()
cursor.execute("SELECT * FROM academic_performance WHERE exam_score > 90")
cursor.fetchall()
print("‚è±Ô∏è Time without index:", time.time() - start)

# Create index on exam_score
cursor.execute("CREATE INDEX idx_exam_score ON academic_performance(exam_score)")

# Query after index
start = time.time()
cursor.execute("SELECT * FROM academic_performance WHERE exam_score > 90")
cursor.fetchall()
print("‚è±Ô∏è Time with index:", time.time() - start)

‚è±Ô∏è Time without index: 0.002010345458984375
‚è±Ô∏è Time with index: 0.00027298927307128906

---------------------------------------------------------------------------------------------------------------
 # üóÉÔ∏è Phase 2: NoSQL Database using TinyDB

In [17]:
# Install TinyDB
!pip install tinydb

# TinyDB process
from tinydb import TinyDB, Query
from tinydb.operations import set
df_nosql = pd.read_csv('/content/StudentPerformanceFactors.csv')

# Create and reset TinyDB
db = TinyDB('/content/student_performance_tinydb.json')
db.drop_tables()

#Insert selected columns as records
student_docs = df[[
    'Student_Id', 'Gender', 'Internet_Access', 'Parental_Education_Level',
    'Family_Income', 'Learning_Disabilities'
]].to_dict(orient='records')

db.insert_multiple(student_docs)
print(f"‚úÖ Inserted {len(student_docs)} records into TinyDB.")

Collecting tinydb
  Downloading tinydb-4.8.2-py3-none-any.whl.metadata (6.7 kB)
Downloading tinydb-4.8.2-py3-none-any.whl (24 kB)
Installing collected packages: tinydb
Successfully installed tinydb-4.8.2
‚úÖ Inserted 6607 records into TinyDB.

## TinyDB Queries

In [18]:
Student = Query()

# Find students who have access to Internet
result1 = db.search(Student.Internet_Access == 'Yes')
print("üìò Students who have access to Internet:", len(result1))

üìò Students who have access to Internet: 6108

In [19]:
# Find students with low family income
low_income = db.search(Student.Family_Income == 'Low')

# Convert result to DataFrame for table display
df_low_income = pd.DataFrame(low_income)

# Show results
print("üí∞ Students with Low Family Income (Total:", len(low_income), "):")
print(df_low_income.head(10))  # Display first 10 results only

üí∞ Students with Low Family Income (Total: 2672 ):
   Student_Id  Gender Internet_Access Parental_Education_Level Family_Income  \
0        4429    Male             Yes              High School           Low
1        4400    Male             Yes              High School           Low
2        8671    Male             Yes              High School           Low
3        5993    Male             Yes             Postgraduate           Low
4        3546  Female             Yes              High School           Low
5        5227  Female             Yes                  College           Low
6        6590    Male             Yes              High School           Low
7        1387  Female             Yes              High School           Low
8        8770  Female             Yes              High School           Low
9        5987    Male             Yes                  College           Low

  Learning_Disabilities
0                    No
1                    No
2                    No
3                    No
4                    No
5                    No
6                    No
7                    No
8                    No
9                    No

In [20]:
# Find students with learning disabilities
disabilities = db.search(Student.Learning_Disabilities == 'Yes')

# Convert result to DataFrame for display
df_disabilities = pd.DataFrame(disabilities)

# Print summary and show table
print("üß† Students with Learning Disabilities (Total:", len(disabilities), "):")
print(df_disabilities.head(10))  # Display first 10 entries only

üß† Students with Learning Disabilities (Total: 695 ):
   Student_Id  Gender Internet_Access Parental_Education_Level Family_Income  \
0        1323  Female             Yes              High School          High
1        5958  Female             Yes              High School          High
2        4939  Female             Yes                  College        Medium
3        8166    Male             Yes                  College        Medium
4        3498  Female             Yes             Postgraduate          High
5        4369  Female              No              High School        Medium
6        1397    Male             Yes                  College          High
7        6826    Male             Yes                  College        Medium
8        3877  Female             Yes              High School        Medium
9        2487    Male             Yes              High School        Medium

  Learning_Disabilities
0                   Yes
1                   Yes
2                   Yes
3                   Yes
4                   Yes
5                   Yes
6                   Yes
7                   Yes
8                   Yes
9                   Yes

## TinyDB Updates and Filters

In [21]:
# Update the internet access to "No" for student with ID 4429
db.update(set('Internet_Access', 'No'), Student.Student_Id == 4429)

# Verify the update
updated_student = db.search(Student.Student_Id == 4429)
print("üîÑ Updated Student:", updated_student)

üîÑ Updated Student: [{'Student_Id': 4429, 'Gender': 'Male', 'Internet_Access': 'No', 'Parental_Education_Level': 'High School', 'Family_Income': 'Low', 'Learning_Disabilities': 'No'}]

In [22]:
# Delete the student document where Student_Id is 1095
db.remove(Student.Student_Id == 1095)


# Check if student was removed
deleted_check = db.search(Student.Student_Id == 1095)
print("üóëÔ∏è Deleted Student Exists?:", bool(deleted_check))  # Should return False

üóëÔ∏è Deleted Student Exists?: False

In [23]:
results = db.search((Student.Internet_Access == 'Yes') & (Student.Family_Income == 'Low'))
print("üì° Students with internet AND low income:", len(results))

üì° Students with internet AND low income: 2460

---------------------------------------------------------------------------------------------
# ‚ö° Phase 3: Stream Processing using PySpark

In [24]:
# Install PySpark
!pip install -q pyspark

# Import PySpark
from pyspark.sql import SparkSession
from pyspark.sql.functions import col

# Create Spark session
spark = SparkSession.builder.appName("StudentStream").getOrCreate()

# Read CSV stream data
df_stream = spark.read.option("header", True).csv("/content/StudentPerformanceFactors.csv")
df_stream.show()

+-------------+----------+--------------------+-------------------+--------------------------+-----------+---------------+----------------+---------------+-----------------+-------------+---------------+-----------+--------------+-----------------+---------------------+------------------------+------------------+------+----------+----------+-----------+
|Hours_Studied|Attendance|Parental_Involvement|Access_to_Resources|Extracurricular_Activities|Sleep_Hours|Previous_Scores|Motivation_Level|Internet_Access|Tutoring_Sessions|Family_Income|Teacher_Quality|School_Type|Peer_Influence|Physical_Activity|Learning_Disabilities|Parental_Education_Level|Distance_from_Home|Gender|Exam_Score|Student_Id|Acadamic_No|
+-------------+----------+--------------------+-------------------+--------------------------+-----------+---------------+----------------+---------------+-----------------+-------------+---------------+-----------+--------------+-----------------+---------------------+------------------------+------------------+------+----------+----------+-----------+
|           23|        84|                 Low|               High|                        No|          7|             73|             Low|            Yes|                0|          Low|         Medium|     Public|      Positive|                3|                   No|             High School|              Near|  Male|        67|      4429|          1|
|           19|        64|                 Low|             Medium|                        No|          8|             59|             Low|            Yes|                2|       Medium|         Medium|     Public|      Negative|                4|                   No|                 College|          Moderate|Female|        61|      1095|          2|
|           24|        98|              Medium|             Medium|                       Yes|          7|             91|          Medium|            Yes|                2|       Medium|         Medium|     Public|       Neutral|                4|                   No|            Postgraduate|              Near|  Male|        74|      4180|          3|
|           29|        89|                 Low|             Medium|                       Yes|          8|             98|          Medium|            Yes|                1|       Medium|         Medium|     Public|      Negative|                4|                   No|             High School|          Moderate|  Male|        71|      9675|          4|
|           19|        92|              Medium|             Medium|                       Yes|          6|             65|          Medium|            Yes|                3|       Medium|           High|     Public|       Neutral|                4|                   No|                 College|              Near|Female|        70|      4722|          5|
|           19|        88|              Medium|             Medium|                       Yes|          8|             89|          Medium|            Yes|                3|       Medium|         Medium|     Public|      Positive|                3|                   No|            Postgraduate|              Near|  Male|        71|      2336|          6|
|           29|        84|              Medium|                Low|                       Yes|          7|             68|             Low|            Yes|                1|          Low|         Medium|    Private|       Neutral|                2|                   No|             High School|          Moderate|  Male|        67|      4400|          7|
|           25|        78|                 Low|               High|                       Yes|          6|             50|          Medium|            Yes|                1|         High|           High|     Public|      Negative|                2|                   No|             High School|               Far|  Male|        66|      6989|          8|
|           17|        94|              Medium|               High|                        No|          6|             80|            High|            Yes|                0|       Medium|            Low|    Private|       Neutral|                1|                   No|                 College|              Near|  Male|        69|      6616|          9|
|           23|        98|              Medium|             Medium|                       Yes|          8|             71|          Medium|            Yes|                0|         High|           High|     Public|      Positive|                5|                   No|             High School|          Moderate|  Male|        72|      2612|         10|
|           17|        80|                 Low|               High|                        No|          8|             88|          Medium|             No|                4|       Medium|           High|    Private|       Neutral|                4|                   No|                 College|          Moderate|  Male|        68|      7184|         11|
|           17|        97|              Medium|               High|                       Yes|          6|             87|             Low|            Yes|                2|          Low|           High|    Private|       Neutral|                2|                   No|             High School|              Near|  Male|        71|      8671|         12|
|           21|        83|              Medium|             Medium|                       Yes|          8|             97|             Low|            Yes|                2|       Medium|         Medium|     Public|      Positive|                4|                   No|             High School|              Near|  Male|        70|      2172|         13|
|            9|        82|              Medium|             Medium|                       Yes|          8|             72|          Medium|            Yes|                2|       Medium|         Medium|    Private|      Positive|                3|                   No|            Postgraduate|              Near|  Male|        66|      2446|         14|
|           10|        78|              Medium|               High|                       Yes|          8|             74|          Medium|            Yes|                1|          Low|         Medium|    Private|       Neutral|                4|                   No|            Postgraduate|              Near|  Male|        65|      5993|         15|
|           17|        68|              Medium|             Medium|                        No|          8|             70|          Medium|            Yes|                2|       Medium|         Medium|    Private|      Positive|                4|                   No|             High School|              Near|Female|        64|      4108|         16|
|           14|        60|              Medium|                Low|                       Yes|         10|             65|             Low|            Yes|                0|         High|         Medium|    Private|      Positive|                3|                   No|                 College|              Near|  Male|        60|      4002|         17|
|           22|        70|                 Low|             Medium|                       Yes|          6|             82|          Medium|            Yes|                1|          Low|           High|     Public|       Neutral|                3|                   No|             High School|              Near|Female|        65|      3546|         18|
|           15|        80|              Medium|             Medium|                       Yes|          9|             91|             Low|            Yes|                3|          Low|         Medium|     Public|      Positive|                2|                   No|                 College|          Moderate|Female|        67|      5227|         19|
|           12|        75|              Medium|               High|                       Yes|          7|             58|          Medium|            Yes|                3|       Medium|         Medium|    Private|      Positive|                4|                   No|                 College|              Near|  Male|        66|      2422|         20|
+-------------+----------+--------------------+-------------------+--------------------------+-----------+---------------+----------------+---------------+-----------------+-------------+---------------+-----------+--------------+-----------------+---------------------+------------------------+------------------+------+----------+----------+-----------+
only showing top 20 rows

In [25]:

#  Filter students who studied more than 20 hours and attended more than 90%
filtered_df = df_stream.filter(
    (col("Hours_Studied").cast("int") > 20) &
    (col("Attendance").cast("int") > 90)
)
# Show results
print("üìä Students who studied more than 20 hours and attended more than 90%:")
filtered_df.show()

# Save filtered students
output_path =  "/content/filtered_students"
filtered_df.write.option("header", True).mode("overwrite").csv(output_path)


# Verify file was saved
import os
print("Files saved to:", os.listdir(output_path))

üìä Students who studied more than 20 hours and attended more than 90%:
+-------------+----------+--------------------+-------------------+--------------------------+-----------+---------------+----------------+---------------+-----------------+-------------+---------------+-----------+--------------+-----------------+---------------------+------------------------+------------------+------+----------+----------+-----------+
|Hours_Studied|Attendance|Parental_Involvement|Access_to_Resources|Extracurricular_Activities|Sleep_Hours|Previous_Scores|Motivation_Level|Internet_Access|Tutoring_Sessions|Family_Income|Teacher_Quality|School_Type|Peer_Influence|Physical_Activity|Learning_Disabilities|Parental_Education_Level|Distance_from_Home|Gender|Exam_Score|Student_Id|Acadamic_No|
+-------------+----------+--------------------+-------------------+--------------------------+-----------+---------------+----------------+---------------+-----------------+-------------+---------------+-----------+--------------+-----------------+---------------------+------------------------+------------------+------+----------+----------+-----------+
|           24|        98|              Medium|             Medium|                       Yes|          7|             91|          Medium|            Yes|                2|       Medium|         Medium|     Public|       Neutral|                4|                   No|            Postgraduate|              Near|  Male|        74|      4180|          3|
|           23|        98|              Medium|             Medium|                       Yes|          8|             71|          Medium|            Yes|                0|         High|           High|     Public|      Positive|                5|                   No|             High School|          Moderate|  Male|        72|      2612|         10|
|           26|        91|              Medium|                Low|                       Yes|          8|             71|          Medium|            Yes|                0|          Low|         Medium|    Private|       Neutral|                3|                   No|             High School|          Moderate|  Male|        68|      6174|         60|
|           25|        98|                 Low|               High|                       Yes|          8|             56|          Medium|             No|                0|       Medium|           High|    Private|       Neutral|                3|                   No|            Postgraduate|              Near|  Male|        71|      6637|         65|
|           22|        98|              Medium|               High|                        No|          5|             69|             Low|             No|                1|          Low|           High|     Public|      Negative|                4|                   No|             High School|          Moderate|Female|        69|      9569|         69|
|           22|        98|              Medium|                Low|                       Yes|          7|             52|          Medium|             No|                3|       Medium|         Medium|     Public|      Positive|                3|                   No|                 College|              Near|Female|        70|      4182|         71|
|           29|        96|              Medium|                Low|                       Yes|          7|             72|          Medium|            Yes|                1|          Low|         Medium|     Public|      Positive|                3|                   No|             High School|          Moderate|  Male|        71|      5554|         72|
|           29|        92|                 Low|             Medium|                        No|          4|             91|          Medium|            Yes|                2|       Medium|         Medium|     Public|      Negative|                1|                   No|            Postgraduate|              Near|Female|        72|      4259|         74|
|           23|        98|              Medium|                Low|                       Yes|          7|             54|             Low|            Yes|                0|       Medium|         Medium|     Public|      Negative|                3|                   No|                 College|              Near|Female|        68|      5764|         90|
|           22|        99|              Medium|                Low|                       Yes|          6|             92|             Low|            Yes|                3|       Medium|         Medium|     Public|      Negative|                4|                   No|            Postgraduate|          Moderate|  Male|        72|      7630|        106|
|           31|       100|              Medium|             Medium|                        No|          7|             59|          Medium|            Yes|                2|         High|           High|     Public|      Positive|                5|                   No|            Postgraduate|          Moderate|  Male|        76|      2159|        107|
|           35|        99|                High|               High|                       Yes|          7|             85|             Low|            Yes|                2|       Medium|           High|    Private|       Neutral|                2|                   No|            Postgraduate|              Near|Female|        79|      3981|        114|
|           27|        97|                 Low|               High|                       Yes|          8|             81|          Medium|            Yes|                0|         High|         Medium|     Public|      Positive|                5|                   No|             High School|              Near|Female|        73|      8520|        119|
|           21|        96|              Medium|             Medium|                        No|          8|             64|            High|            Yes|                2|       Medium|           High|     Public|       Neutral|                0|                   No|                 College|              Near|  Male|        71|      9603|        141|
|           21|        91|                High|             Medium|                        No|          6|            100|          Medium|            Yes|                0|         High|         Medium|    Private|       Neutral|                2|                   No|            Postgraduate|              Near|Female|        72|      2557|        144|
|           22|        95|              Medium|               High|                       Yes|          6|             69|          Medium|            Yes|                1|          Low|         Medium|     Public|      Positive|                3|                   No|                 College|              Near|Female|        72|      5209|        150|
|           31|        92|              Medium|             Medium|                       Yes|          4|             76|          Medium|            Yes|                2|       Medium|           High|     Public|      Positive|                4|                  Yes|             High School|               Far|  Male|        72|      8748|        157|
|           22|        95|              Medium|               High|                        No|          9|             88|             Low|            Yes|                0|          Low|           High|     Public|      Positive|                2|                   No|            Postgraduate|              Near|  Male|        72|      1223|        174|
|           29|        96|              Medium|             Medium|                       Yes|          9|             55|             Low|             No|                0|       Medium|         Medium|     Public|       Neutral|                2|                   No|            Postgraduate|               Far|Female|        70|      9942|        178|
|           25|        91|              Medium|             Medium|                        No|          8|             72|             Low|            Yes|                2|       Medium|           High|     Public|      Positive|                0|                   No|            Postgraduate|              Near|  Male|        71|      6366|        192|
+-------------+----------+--------------------+-------------------+--------------------------+-----------+---------------+----------------+---------------+-----------------+-------------+---------------+-----------+--------------+-----------------+---------------------+------------------------+------------------+------+----------+----------+-----------+
only showing top 20 rows

Files saved to: ['part-00000-133a2069-4821-4bbf-af77-e54cfe959bad-c000.csv', '.part-00000-133a2069-4821-4bbf-af77-e54cfe959bad-c000.csv.crc', '_SUCCESS', '._SUCCESS.crc']

## Conclusion

In this project, we successfully designed and implemented a complete data engineering pipeline to manage and analyze student performance data. The solution was developed in four phases, each focusing on a key component of modern data processing:

üóÑÔ∏è SQLite was used for relational storage, normalization, and performing advanced SQL queries such as CRUD operations, joins, indexing, and aggregations.

üóÉÔ∏è TinyDB provided a lightweight and flexible NoSQL-style document store that allowed us to model unstructured student attributes and perform document-based queries.

‚ö° PySpark enabled scalable data filtering and processing on simulated streaming data using a CSV file, showcasing how big data frameworks can handle high-volume processing efficiently.

Each phase contributed to building a real-world data pipeline and helped us understand the strengths of different tools in the data engineering ecosystem. This project reinforced the importance of integrating multiple technologies to extract meaningful insights from complex data sources.